import LocalizedStrings from "react-native-localization";

let Localized = new LocalizedStrings({
    en: {
        summary: "Summary",
        orders: "Orders",
        statistics: "Statistics",
        hello: "Hello!",
        mainpage: "Mainpage",
        myorders: "My orders",
        profile: "Profile",
        contact: "Contact",
        terms_of_use: "Terms of Use",
        email: "Email",
        name: "Name",
        restaurant_name: "Restaurant Name",
        password: "Password",
        first_name: "First name",
        last_name: "Last name",
        min_6_chars: "Minimum 6 characters!",
        incorrect_email: "Incorrect email address!",
        incorrect_name: "Incorrect name",
        incorrect_restaurant_name: "Restaurant name cant be blank",
        incorrect_phone: "Phone number cant be blank",
        fill_all_field: "Fill all required field!",
        unsuccessful_login: "Login failed!",
        successful_login: "SUCCESSFUL LOGIN!",
        unsuccessful_reg: "Registration failed!",
        successful_reg: "SUCCESSFUL REGISTRATION!",
        login: "Login",
        registration: "Registration",
        register: "Register",
        forgotten_pass: "Forgotten password",
        email_not_existing: "There is no registration with the given email address!",
        failed_operation: "Failed operation!",
        email_sent: "Your password reminder has been sent to the given email address!",
        enter_email: "Enter your email address",
        city: "City",
        street: "Street",
        premise_number: "House number",
        floor: "Floor",
        door: "Door",
        doorbell: "Doorbell",
        select_city: "Select a city!",
        select_street: "Select street!",
        featured_promotions: "Featured product",
        further: "Further ",
        no_order: "We can't take orders currently",
        terms: "TERMS",
        privacy: "PRIVACY",
        cart_total: "Total:",
        delivery_fee: "delivery: ",
        min_order_price_warning: "The minimum order price for this restaurant is:",
        min_order_price_region: "The minimum order price for the region is: ",
        cart: "Cart",
        credit_card_on_delivery: "Credit card on delivery",
        cash_on_delivery: "Cash on delivery",
        cash_sit_in: "Cash sit in",
        //szep_kartya: 'SZÉP kártyával futárnak',
        szep_kartya: "OTP SZÉP Kártya",
        erzsebet_utalvany: "Erzsébet utalvány",
        sodexo: "Sodexo",
        ticket_express: "Ticket Express",
        barion: "Online payment (Barion)",
        simplepay: "Online payment (OTP)",
        szep_kartya_web: "OTP SZÉP kártya Online",
        erzsebet_plusz: "Erzsébet Plusz",
        credit_card_sit_in: "Credit card sit in",
        barion_email: "Barion Email",
        kah_szep_web: "K&H Szépkártya web",
        mkb_szep_web: "MKB Szépkártya web",
        simplepay_merchant_id: "Simplepay merhant id",
        pizzagyar_pizza_coupon: "Pizzagyár pizza kupon",
        sms: "SMS",
        braintree: "BrainTree",
        stripe: "Stripe",
        credit_card_phone: "Credit Card Phone",
        szep_kartya_sit_in: "Szép Kártya Sit In",
        szep_kartya_phone: "Szép Kártya Phone",
        mkb_szep_sit_in: "MKB Szép Kártya Sit In",
        mkb_szep_phone: "MKB Szép Kártya Phone",
        otp_szep_on_delivery: "OTP Szép Kártya on delivery",
        kah_szep_on_delivery: "K&H Szép Kártya on delivery",
        mkb_szep_on_delivery: "MKB Szép Kártya on delivery",
        otp_szep_sit_in: "OTP Szép Kártya sit in",
        otp_szep_phone: "OTP Szép Kártya phone",
        kah_szep_sit_in: "K&H Szép kártya sit in",
        kah_szep_phone: "K&H Szép Kártya Phone",
        utalvany: "Voucher",
        netpincer_card: "Netpincer credit card",
        netpincer_szep: "Netpincer Szép Kártya",
        cash_phone: "Cash Phone",
        archived: "Archived",
        payment_method: "Payment method",
        platform: "Platform",
        segment: "Grouping aspect",
        comment: "Comment",
        cancel_payment: "Cancel Payment",
        cancel: "Cancel",
        got_your_order: "We have got your order! Thank You!",
        unsuccessful_payment: "Unsuccessful payment!",
        send: "Send",
        unsuccessful_logout: "Logout failed!",
        saved_addresses: "Saved addresses",
        new_address: "New address",
        logout: "Logout",
        save: "Save",
        delete: "Delete",
        address_name: "Address name",
        save_failed: "Save failed!",
        successful_address_update: "Successful address update",
        attention: "ATTENTION",
        yes: "YES",
        no: "NO",
        delete_address_question: "Do you want to delete the selected address?",
        logout_question: "Do you want to logout?",
        order_failed: "Order failed! Please try again later!",
        order_failed_short: "FAILED",
        /*order_infos: 'Order informations',*/
        order_infos: "Order",
        order_it: "Order",
        order_status: "ORDER STATUS",
        received: "received",
        processed: "processed",
        succeeded: "succeeded",
        storno: "storno",
        storno_filter: "cancelled",
        discount_filter: "discounted",
        order_prepared: "PREPARED",
        no_prev_order: "NO ORDER TO DISPLAY",
        select_address: "Select address please!",
        back: "Back",
        //extras: 'Extras',
        extras: "Options",
        //no_extras: 'No extras for this food',
        no_extras: "No options for this food",
        food_comment: "+ comment",
        network_error: "Network error! Pleasy try again later!",
        retry: "RETRY",
        no_internet_connection: "No internet connection",
        you_are_offline: "Your device is in offline mode or check your internet connection",
        i_ll_eat_this: "I'll eat this",
        coupon: "coupon",
        checkout: "Go to checkout",
        invalid_coupon_code: "Invalid coupon code",
        coupon_activated: "Coupon activated",
        empty_coupon: "Please write something in the Coupon field",
        item_added_to_cart: "You added the item to your cart:",
        continue_shopping: "Would you like to continue shopping?",
        yes_i_want_more: "Yes, I want more!",
        go_to_cart: "Go, to cart",
        comment_to_your_food: "comment for this product",
        write_coupon_code: "Please write in the coupon code",
        coupon_code: "Coupon code",
        are_you_sure_to_delete_item: "Are you sure you delete this item from your cart?",
        yes_notcap: "Yes",
        empty_your_cart: "Are you sure you want to empty your cart?",
        order_again: "ORDER AGAIN",
        successful_order: "Successful order!",
        order: "ORDER: ",
        comment2: "COMMENT: ",
        min_no_options_warn: "Please, check the following: ",
        empty_cart: "Your cart is empty!",
        search: "Search...",
        app_disabled: "The app is temporarily suspended!",
        visit_web: "Please visit the webpage, if you would like to order!",
        open_page: "OPEN WEB",
        update_app: "Update the application!",
        update: "UPDATE",
        categories: "Categories",
        cancel_payment_title: "If you leave this page, the order will be unsuccesful!",
        no_street: "No street found!",
        restaurant: "Restaurant",
        rest_chooser: "Restaurant chooser",
        done: "DONE",
        select_city: "Select city!",
        saved_addresses_warning:
            "Your addresses marked with red are not available in this restaurant!",
        cant_order_to_this_address:
            "The restaurant is not delivering orders to this address at the moment!",
        tracking_title: "Tracking",
        estimated_delivery_time: "Estimated delivery time",
        minutes: "minutes",
        orders_number: "Your orders number",
        orders_before_yours: "Orders before yours",
        no_orders_to_track: "You have no orders to track at this moment!",
        android: "Android",
        ios: "iOS",
        browser: "Browser",
        browser_ios: "Browser iOS",
        browser_android: "Browser android",
        facebook: "Facebook",
        messenger: "Messenger",
        sit_in: "Sit in",
        take_away: "Take away",
        phone_number: "Phone",
        pizzahu: "Pizza.hu",
        ordit: "Ord.it",
        netpincer: "Netpincer",
        orders_total_title: "Orders total:",
        sit_in_orders_title: "Sit-in orders:",
        take_away_orders_title: "Take away orders:",
        deliveries_title: "Orders for delivery:",
        day: "Day",
        interval: "Interval",
        close: "Close",
        too_long_interval: "You can't select more than 31 days",
        your_restaurants: "Your restaurants:",
        piece: "pcs",
        go_to_website: "Go to my webpage",
        choose_segment_by: "Grouping aspects",
        product_categories: "Product Categories",
        products: "Products",
        subproducts: "Subproducts",
        pieces_title: "Ordered products:",
        pieces: "pcs.",
        average: "Average price in category:",
        users: "Users",
        users_total: "Users: ",
        users_new: "New users in this time period: ",
        options: "Options",
        thank_you_for_reg:
            "Thank you for your registration, you can log in after the admins approve your account!",
        no_orders_to_show: "There are no orders to show",
        no_permisson:
            "Sorry you don't have permission to use this app with this login credentials.",
        update_app: "There's a new version of this application. Please update!"
    },
    hu: {
        summary: "Összesítés",
        orders: "Rendelések",
        statistics: "Statisztika",
        hello: "Csá",
        mainpage: "Főoldal",
        myorders: "Rendeléseim",
        profile: "Profilom",
        contact: "Kapcsolat",
        terms_of_use: "Á.SZ.F",
        email: "Email",
        name: "Név",
        restaurant_name: "Étterem neve",
        password: "Jelszó",
        first_name: "Keresztnév",
        last_name: "Vezetéknév",
        phone_number: "Telefonszám",
        min_6_chars: "Minimum 6 karakter!",
        incorrect_email: "Hibás email cím!",
        incorrect_name: "Hibás név",
        incorrect_restaurant_name: "Az étterem neve nem lehet üres",
        incorrect_phone: "Telefonszám nem lehet üres",
        fill_all_field: "Töltsön ki minden kötelező mezőt!",
        unsuccessful_login: "Sikertelen bejelentkezés!",
        successful_login: "SIKERES BEJELENTKEZÉS!",
        unsuccessful_reg: "Sikertelen regisztráció!",
        successful_reg: "SIKERES REGISZTRÁCIÓ!",
        login: "Bejelentkezés",
        registration: "Regisztráció",
        register: "Regisztrálok",
        forgotten_pass: "Elfelejtett jelszó",
        email_not_existing: "A megadott email címmel nem létezik regisztráció!",
        failed_operation: "Sikertelen művelet!",
        email_sent: "Jelszóemlékeztetőjét elküldtük a megadott email címre!",
        enter_email: "Írja be email címét",
        phone: "Telefonszám",
        city: "Város",
        street: "Utca",
        premise_number: "Házszám",
        floor: "Emelet",
        door: "Ajtó",
        doorbell: "Kapucsengő",
        select_city: "Válasszon várost!",
        select_street: "Válasszon utcát!",
        featured_promotions: "Kiemelt termékünk",
        further: "További ",
        no_order: "Az étterem jelenleg nem fogad rendeléseket!",
        terms: "Á.SZ.F",
        privacy: "ADATVÉDELEM",
        cart_total: "Összesen:",
        delivery_fee: "szállítás: ",
        min_order_price_warning: "A minimum rendelési összeg ennél az étteremnél:",
        min_order_price_region: "A minimum rendelési összeg a régióra: ",
        cart: "Kosár",
        credit_card_on_delivery: "Bankkártyával futárnak",
        cash_on_delivery: "Készpénz",
        cash_sit_in: "Helyben Készpénzzel",
        szep_kartya: "SZÉP kártyával futárnak",
        erzsebet_utalvany: "Erzsébet utalvány",
        sodexo: "Sodexo",
        ticket_express: "Ticket Express",
        barion: "Online fizetés (Barion)",
        simplepay: "Online fizetés (OTP)",
        szep_kartya_web: "OTP SZÉP kártya Online",
        erzsebet_plusz: "Erzsébet Plusz",
        credit_card_sit_in: "Helyben Bankkártyával",
        barion_email: "Barion Email",
        kah_szep_web: "K&H Szépkártya web",
        mkb_szep_web: "MKB Szépkártya web",
        simplepay_merchant_id: "Simplepay merhant id",
        pizzagyar_pizza_coupon: "Pizzagyár pizza kupon",
        sms: "SMS",
        braintree: "BrainTree",
        stripe: "Stripe",
        credit_card_phone: "Telefonos Bankkártya",
        szep_kartya_sit_in: "Beülős Szép Kártya",
        szep_kartya_phone: "Telefonos Szép Kártya",
        mkb_szep_sit_in: "Beülős MKB Szép Kártya",
        mkb_szep_phone: "Telefonos MKB Szép Kártya",
        otp_szep_on_delivery: "OTP Szép Kártya futárnál",
        kah_szep_on_delivery: "K&H Szép Kártya futárnál",
        mkb_szep_on_delivery: "MKB Szép Kártya futárnál",
        otp_szep_sit_in: "Beülős OTP Szép Kártya",
        otp_szep_phone: "Telefonos OTP Szép Kártya",
        kah_szep_sit_in: "Beülős K&H Szép kártya",
        kah_szep_phone: "Telefonos K&H Szép Kártya",
        utalvany: "Utalvány",
        netpincer_card: "Netpincer Bankkártya",
        netpincer_szep: "Netpincer Szép Kártya",
        cash_phone: "Telefonos Készpénz",
        archived: "Archivált",
        payment_method: "Fizetési mód",
        segment: "Csoportosítási szempont",
        platform: "Platform",
        comment: "Megjegyzés",
        cancel_payment: "Fizetés félbeszakítása",
        cancel: "Mégse",
        got_your_order: "Rendelését megkaptuk! Köszönjük!",
        unsuccessful_payment: "Sikertelen fizetés!",
        send: "Küldés",
        unsuccessful_logout: "Sikertelen kijelentkezés!",
        saved_addresses: "Mentett címek",
        new_address: "Új cím",
        logout: "Kijelentkezés",
        save: "Mentés",
        delete: "Törlés",
        address_name: "Cím neve",
        save_failed: "Sikertelen mentés!",
        successful_address_update: "Sikeres címfrissítés",
        attention: "FIGYELEM",
        yes: "IGEN",
        no: "NEM",
        delete_address_question: "Biztosan törli a kijelölt címet?",
        logout_question: "Biztosan kijelentkezik?",
        order_failed: "Sikertelen rendelés! Próbálja meg később!",
        order_failed_short: "SIKERTELEN",
        order_infos: /*'Rendelés Információk',*/ "Rendelés",
        order_it: "Megrendelem",
        order_status: "RENDELÉS ÁLLAPOTA",
        received: "feldolgozás alatt",
        processed: "feldolgozva",
        succeeded: "függőben",
        storno: "sztornó",
        storno_filter: "sztornózottak",
        discount_filter: "kedvezményezettek",
        order_prepared: "ELŐKÉSZÍTVE",
        no_prev_order: "NINCS MEGJELENÍTHETŐ RENDELÉSE",
        select_address: "Válasszon címet!",
        back: "Vissza",
        //extras: 'Extra feltétek',
        extras: "Opciók",
        //no_extras: 'Nincsenek extra feltétek',
        no_extras: "Nincsenek opciók",
        food_comment: "+ megjegyzés",
        network_error: "Hálózati hiba! Próbálja újra később!",
        retry: "ÚJRAPRÓBÁLKOZÁS",
        no_internet_connection: "Nincs internetkapcsolat",
        you_are_offline: "Offile állapotban van vagy ellenőrizze internetkapcsolatát",
        i_ll_eat_this: "Megeszem",
        coupon: "kupon",
        checkout: "Tovább a rendeléshez",
        invalid_coupon_code: "Érvénytelen kuponkód",
        coupon_activated: "Kupon aktiválva",
        empty_coupon: "Kérlek töltsd ki a Kuponkód mezőt",
        item_added_to_cart: "A terméket hozzáadtad a kosárhoz:",
        continue_shopping: "Szeretnéd folytatni a vásárlást?",
        yes_i_want_more: "Igen, kérek mást is",
        go_to_cart: "Megrendelem",
        comment_to_your_food: "megyjegyzés az étellel kapcsolatban",
        write_coupon_code: "Kérlek írd be a kuponkódot",
        coupon_code: "Kuponkód",
        are_you_sure_to_delete_item: "Biztosan törlöd ezt az elemet a kosaradból?",
        yes_notcap: "Igen",
        empty_your_cart: "Biztosan kiüríted a kosarad?",
        order_again: "MEGRENDELEM ÚJRA",
        successful_order: "Sikeres rendelés!",
        order: "RENDELÉS: ",
        comment2: "MEGJEGYZÉS: ",
        min_no_options_warn: "Kérlek ellenőrizd, az alábbiakat: ",
        empty_cart: "Üres a kosarad!",
        search: "Keresés...",
        app_disabled: "A rendelés ideiglenesen szünetel!",
        visit_web: "Kérjük látogassa meg weboldalunkat, ha rendelni szeretne!",
        open_page: "MEGNYITÁS",
        update_app: "Frissítse az applikációt!",
        update: "FRISSÍTÉS",
        categories: "Kategóriák",
        cancel_payment_title: "Ha visszalép, rendelése sikertelen lesz!",
        no_street: "Nincs ilyen utca!",
        restaurant: "Étterem",
        rest_chooser: "Étterem választó",
        done: "TOVÁBB",
        select_city: "Válassz várost!",
        saved_addresses_warning: "A pirossal jelölt címeidre nem szállít ez az étterem!",
        cant_order_to_this_address: "A kiválasztott címre nem szállít jelenleg az étterem!",
        tracking_title: "Futárkövetés",
        estimated_delivery_time: "Várható szállítási idő",
        minutes: "perc",
        orders_number: "Hanyadik rendelés a tiéd",
        orders_before_yours: "Hány rendelés van előtted",
        no_orders_to_track: "Jelenleg nincs nyomon kovethető rendelésed!",
        android: "Android",
        ios: "iOS",
        browser: "Böngésző",
        browser_ios: "Böngésző iOS",
        browser_android: "Böngésző android",
        facebook: "Facebook",
        messenger: "Messenger",
        sit_in: "Beülős",
        take_away: "Elviteles",
        phone: "Telefonos",
        pizzahu: "Pizza.hu",
        ordit: "Ord.it",
        netpincer: "Netpincér",
        orders_total_title: "Összes rendelés:",
        sit_in_orders_title: "Helyben fogyasztott:",
        take_away_orders_title: "Elvitel:",
        deliveries_title: "Kiszállítás:",
        day: "Nap",
        interval: "Intervallum",
        close: "Bezárás",
        too_long_interval: "Maximum 31 napot választhatsz ki!",
        your_restaurants: "Éttermeid:",
        piece: "db",
        go_to_website: "Irány a weboldalam",
        choose_segment_by: "Csoportosítási szempontok",
        product_categories: "Termék Kategóriák",
        products: "Termékek",
        subproducts: "Termékvariációk",
        pieces_title: "Megrendelt termékek:",
        pieces: "db",
        average: "Kategórián belüli költés átlaga:",
        users: "Felhasználók",
        users_total: "Felhasználók: ",
        users_new: "Időszakon belüli új felhasználók: ",
        options: "Termékopciók",
        thank_you_for_reg:
            "Köszönjük a regisztrációd, amint jóváhagyták az adminok a fiókodat, be is tudsz lépni!",
        no_orders_to_show: "Nincs megjeleníthető rendelés",
        no_permisson: "Sajnos ezzel a fiókkal nincs jogosultságod az alkalmazás használatához.",
        update_app: "Új verzió érhető el az applikácóból. Kérlek frissítsd!"
    }
});

// 0 android
// 1 ios
// 2 browser
// 3 browser_ios
// 4 browser_android
// 5 facebook
// 6 messenger
// 7 sit_in
// 8 take_away
// 9 phone
// 10 pizzahu
// 11 ordit
// 12 netpincer

module.exports = Localized;
